#!/bin/bash

if [ -n "$JANKY_SHA1" ]; then
  echo "$JANKY_SHA1"
  exit 0
fi

git_revision=$(git rev-parse HEAD)
if [ $? -eq 0 ]; then
  echo "$git_revision"
  exit 0
fi

echo "Could not find revision" >> /dev/stderr
exit 1
