CREATE TABLE `migrations` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `org` varchar(128) NOT NULL,
  `repo` varchar(128) NOT NULL,
  `pull_request_number` bigint(20) unsigned NOT NULL,
  `pull_requests_id` bigint(20) unsigned NOT NULL,
  `pull_request_migration_statements_id` bigint(20) unsigned NOT NULL,
  `mysql_cluster` varchar(128) NOT NULL,
  `mysql_shard` varchar(128) NOT NULL,
  `mysql_schema` varchar(128) NOT NULL,
  `mysql_table` varchar(128) NOT NULL,
  `migration_statement` text NOT NULL,
  `alter_statement` text NOT NULL,
  `suggestion` text NOT NULL,
  `canonical` varchar(128) NOT NULL,
  `strategy` varchar(128) NOT NULL,
  `token` varchar(128) NOT NULL,
  `token_hint` varchar(128) NOT NULL,
  `added_timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ready_timestamp` timestamp NULL DEFAULT NULL,
  `assigned_timestamp` timestamp NULL DEFAULT NULL,
  `started_timestamp` timestamp NULL DEFAULT NULL,
  `liveness_timestamp` timestamp NULL DEFAULT NULL,
  `completed_timestamp` timestamp NULL DEFAULT NULL,
  `status` varchar(128) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `pull_request_migration_statements_id_idx` (`pull_request_migration_statements_id`),
  KEY `mysql_cluster_shard_idx` (`mysql_cluster`,`mysql_shard`),
  KEY `added_timestamp_idx` (`added_timestamp`),
  KEY `token_idx` (`token`),
  KEY `status_idx` (`status`,`liveness_timestamp`),
  KEY `pull_requests_id_idx` (`pull_requests_id`),
  KEY `org_repo_pr_number_idx` (`org`, `repo`, `pull_request_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
